# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('c_num', models.IntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=10, verbose_name='코드 이름')),
            ],
            options={
                'verbose_name': '코드',
                'verbose_name_plural': '코드 모음',
            },
        ),
        migrations.CreateModel(
            name='Code_categ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_name', models.CharField(max_length=10, verbose_name='카테고리 이름')),
            ],
            options={
                'verbose_name': '코드 카테고리',
                'verbose_name_plural': '코드 카테고리 모음',
            },
        ),
        migrations.AddField(
            model_name='code',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codecategory.Code_categ'),
        ),
    ]
