# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codecategory', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='job_select',
        ),
        migrations.AddField(
            model_name='user',
            name='job_selects1',
            field=models.ForeignKey(max_length=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='codecategory.Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_selects2',
            field=models.ForeignKey(max_length=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_selects1', to='codecategory.Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_selects3',
            field=models.ForeignKey(max_length=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_selects2', to='codecategory.Code'),
        ),
    ]
