# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 14:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20180606_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='번호가 맞지 않습니다. 다시확인해주세요!', regex='^\\+?1?\\d{9,15}$')], verbose_name='핸드폰번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.TextField(help_text='간략하게 자기소개를 해주세요!', null=True, verbose_name='자기소개'),
        ),
    ]
