# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20180606_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_selects1',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='codecategory.Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_selects2',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_selects2', to='codecategory.Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_selects3',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_selects3', to='codecategory.Code'),
        ),
    ]
