# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_sancio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='제목')),
                ('motiu_sancio', models.TextField(verbose_name='내용')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('cognom', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='multa',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multes.Persona'),
        ),
    ]
