# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multa',
            name='import_sancio',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='motiu_sancio',
        ),
    ]
