# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0002_auto_20180602_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='companys',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companys',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modify Date'),
        ),
        migrations.AddField(
            model_name='companys',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=2, help_text='one word for title alias.', unique=True, verbose_name='SLUG'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companys',
            name='company_name',
            field=models.CharField(help_text='회사명을 입력해주세요.', max_length=50, verbose_name='회사 이름'),
        ),
        migrations.AlterField(
            model_name='companys',
            name='location',
            field=models.CharField(help_text='회사 주소를 입력해주세요.', max_length=50, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='companys',
            name='occ',
            field=models.CharField(help_text='회사의 주요 업무를 입력해주세요.', max_length=50, verbose_name='업무'),
        ),
        migrations.AlterField(
            model_name='companys',
            name='payment',
            field=models.IntegerField(default=0, help_text='평균 연봉을 입력해주세요.', verbose_name='평균 연봉'),
        ),
        migrations.AlterField(
            model_name='companys',
            name='scale',
            field=models.CharField(choices=[('대기업', '대기업'), ('중소기업', '중소기업'), ('소기업', '소기업')], max_length=50, verbose_name='회사 규모'),
        ),
    ]
