# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0003_auto_20180604_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companys',
            name='slug',
        ),
    ]
