# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0004_remove_companys_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companys',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='modify_date',
        ),
    ]
