# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0008_album_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['album_name']},
        ),
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='album_name',
        ),
    ]
