# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 10:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companys', '0011_auto_20180605_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_pay', models.IntegerField(default=3000)),
            ],
        ),
        migrations.RemoveField(
            model_name='companys',
            name='id',
        ),
        migrations.AlterField(
            model_name='companys',
            name='company_name',
            field=models.CharField(help_text='회사명을 입력해주세요.', max_length=50, primary_key=True, serialize=False, verbose_name='회사 이름'),
        ),
        migrations.AlterField(
            model_name='companys',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pay',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companys.Companys'),
        ),
        migrations.AddField(
            model_name='pay',
            name='mem_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
