# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0012_auto_20180605_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='companys',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companys',
            name='company_name',
            field=models.CharField(help_text='회사명을 입력해주세요.', max_length=50, verbose_name='회사 이름'),
        ),
    ]
