# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0014_remove_pay_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='mem_num',
        ),
        migrations.DeleteModel(
            name='Pay',
        ),
    ]
