# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 10:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companys', '0015_auto_20180605_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_pay', models.IntegerField(default=3000)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companys.Companys')),
                ('mem_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
