# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0018_pay_my_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='my_sum',
        ),
    ]
