# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0019_remove_pay_my_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='my_sum',
            field=models.IntegerField(default=0),
        ),
    ]
