# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20180607_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangoboard',
            name='author',
        ),
        migrations.AlterField(
            model_name='djangoboard',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
